### ISSUE TITLE
GPU is mandatory?

### ISSUE THREAD

**Issue by njss** [imatge-upc/saliency-salgan-2017#7]
Is mandatory to run with a NVIDIA GPU?
Or can we run it using only the cpu?

**Comment by junting** [comment]
Hello @njss ,

The prediction can run on CPU (will be very slow), but is strongly reommended to train the network with GPU, otherwise it will take too long to train. And also for adversarial training, there is part of the code that used `lasagne.layers.dnn.Conv2DDNNLayer` which needs cuDNN to work, if you wish you can replace it with  `lasagne.layers.Conv2DLayer` in order to train with CPU.

Best,
Junting
